### ISSUE TITLE
Unicode и другие опции в API

### ISSUE THREAD

**Issue by proigor** [IlyaDonskikh/smster#1]
Классный gem!

Только с юникоде как быть?
Я прямо в gem добавляю "unicode" => 1, и соответсвенно сообщение конвертирую.

Также, если нужно включить опцию Manage Sender IDs в API.

Но хотелось бы чтобы вы добавили такую опцию в gem, пожалуйста!

**Comment by IlyaDonskikh** [comment]
Спасибо! 

Поясните, пожалуйста, про юникод. Опишите проблему, каким образом решается и для какого провайдера. Также обратите внимание на гем https://github.com/IlyaDonskikh/smster_ruby. На его основе будет построен следующий релиз смстера для реилс.

Ну и ничто так не греет душу разработчика, как звездочка на гитхабе :)

**Comment by proigor** [comment]
Поставил звездочку :)

Использую Clickatell
Посмотрел на код руби гема, там в принципе та же проблема. Вы параметры отдаете только to и number. И не вижу способа через конфиги или еще как-то отправить дополнительные параметры. Если посмотреть на API кликатела, то там много чего можно отправить. У меня без опции unicode русские смс абракадаброй доходят, а еще думаю sender ID нужен будет.

Еще вариант, возможно, я просто туплю и код читать не умею или типо того :)

**Comment by IlyaDonskikh** [comment]
Спасибо, не знал о таком отношении кликателла к русскому языку :)  Расскажите, пожалуйста, про опцию sender ID. 

Не уверен, что на этих выходных дойдет дело до внедрения, а если вы надумаете что-то поменять, то пул-реквест велкам :) Лучше сразу в ядро, то есть сюда: https://github.com/IlyaDonskikh/smster_ruby.

**Comment by proigor** [comment]
Да, приходится и текст кодировать путем
body.codepoints.map { |c| "%04X" % c }.join
и параметр "unicode" => 1 передавать.

Спасибо за предложение. Но это будет первый пул-реквест в опен-сорс проект, чувствую психологически пока не готов :)
Так что все-таки доверил бы доделать вам, когда будет время. А в будущем посмотрим :)

sender ID - это чтобы людям приходило сообщение не от smssms (как у кликатела приходит), а от Igor, Smster и тп, ну вы поняли.

**Comment by IlyaDonskikh** [comment]
Оке, доделаю. Получается, что Sender ID - это текст?

Еще такой вопрос. Получается, что опции юникода не достаточно для корректной передачи сообщения?

**Comment by proigor** [comment]
Спасибо!

Их API:
http://www.clickatell.com/help/apidocs/?_ga=1.134128974.1748414553.1433683117#Message.htm

Source address (Sender ID) - да по ходу текст. Sender ID они еще и заапрувить должны, так что с ним пока не работал, жду пока разрешат, потом уже буду пробовать.

А про мультиязычные смс здесь:
http://www.clickatell.com/help/apidocs/?_ga=1.134128974.1748414553.1433683117#Multi-language_Unicode_Messaging.htm

И там написано
"If this parameter is set the message text must be in hex format. We expect UCS-2 (Big Endian) character set."
Поэтому мне и приходится еще и текст конвертировать.
И еще у них такая штука есть
https://central.clickatell.com/converter/unicode
там тоже об этих шагах написано.

Повторюсь, не претендую на 100% правоту, но пока именно так у меня и работает, с конвертацией текста перед отсылкой и этим параметром unicode.

**Comment by IlyaDonskikh** [comment]
Добавил опцию юникода и сендера. Подробнее смотри вот здесь: https://github.com/IlyaDonskikh/smster_ruby/commit/cac803371068b1b471d56d788177077a3eba4165#diff-af3bf33b6fee81dc992d506af6fea78fL9 (21-22 строки).

Проверь, пожалуйста.

**Comment by proigor** [comment]
Проверил, все отлично, спасибо!

Я мельком взглянул на код, но, кажется, если нужно будет заюзать какой-то другой аргумент из API clickatell, но снова прийдется писать тебе.
Но это так, мелочи жизни и тебе виднее.

Удачи!

**Comment by IlyaDonskikh** [comment]
Пиши, без проблем сделаю.

Я уже в этой версии хотел добавить возможность указания произвольных параметров, но не успел.
